# Generated by Django 2.2.7 on 2020-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meses',
            options={'ordering': ('id', 'mes')},
        ),
    ]
