# Generated by Django 2.2.7 on 2020-02-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200217_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['curso']},
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
    ]
